# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d99ee5dffcdf8dd3ca166bf09f1e29f30a1d9ec6d7d6c374899d2e9f57c247b4e8d18b5865579ae0f35cf3b7d01256ae3d0c5d0825a7220fd9ebd647a4e106

test:
  secret_key_base: 40e005ab3843f4b6d6604286dbd6bf176ee70e971e3dae44da749b842097903371c020fec97fc8ff6c854863da439a293a0a7bcdb64d7ec03f1e5dffccca5aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
